/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurantreviewsystem;

import javax.swing.*;
import java.io.*;

/**
 *
 * @author IMAN ZULHAKIM
 */
public class GUI extends javax.swing.JFrame {

      String cName, cEmail, cPhoneNo;

    public GUI() {

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
        setTitle("Contact Directory System");
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        panelRestaurant = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        btnUploadCSV = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblContactDetails = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        cbSearchType = new javax.swing.JComboBox<>();
        btnDelete = new javax.swing.JButton();
        btnRefreshTable = new javax.swing.JButton();
        txtTitle = new javax.swing.JLabel();
        btnMoveToAddPanel = new javax.swing.JButton();
        cboSortBy = new javax.swing.JComboBox<>();
        cboSortOrder = new javax.swing.JComboBox<>();
        btnSort = new javax.swing.JButton();
        panelAddRestaurant = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPhoneNo = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPhoneNo = new javax.swing.JTextField();
        btnContactList = new javax.swing.JButton();
        panelMenu = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRestaurant.setBackground(new java.awt.Color(153, 204, 255));

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnUploadCSV.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnUploadCSV.setText("UPLOAD");
        btnUploadCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadCSVActionPerformed(evt);
            }
        });

        btnQuit.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnQuit.setText("EXIT");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        tblContactDetails.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        tblContactDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "LOCATION", "CUISINE", "RATINGS"
            }
        ));
        tblContactDetails.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(tblContactDetails);

        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N

        cbSearchType.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        cbSearchType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEARCH BY", "NAME", "LOCATION", "CUISINE", "RATINGS" }));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnRefreshTable.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnRefreshTable.setText("REFRESH");
        btnRefreshTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshTableActionPerformed(evt);
            }
        });

        txtTitle.setBackground(new java.awt.Color(0, 0, 0));
        txtTitle.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        txtTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitle.setText("RESTAURANT REVIEW SYSTEM");

        btnMoveToAddPanel.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnMoveToAddPanel.setText("ADD NEW RESTAURANT");
        btnMoveToAddPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveToAddPanelActionPerformed(evt);
            }
        });

        cboSortBy.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        cboSortBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SORT BY", "NAME", "LOCATION", "CUISINE", "RATINGS" }));

        cboSortOrder.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        cboSortOrder.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ORDER BY", "ASCENDING", "DESCENDING" }));

        btnSort.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnSort.setText("SORT");
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRestaurantLayout = new javax.swing.GroupLayout(panelRestaurant);
        panelRestaurant.setLayout(panelRestaurantLayout);
        panelRestaurantLayout.setHorizontalGroup(
            panelRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRestaurantLayout.createSequentialGroup()
                .addGroup(panelRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRestaurantLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(txtTitle))
                    .addGroup(panelRestaurantLayout.createSequentialGroup()
                        .addGroup(panelRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRestaurantLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(panelRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cboSortBy, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbSearchType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSearch)
                                    .addComponent(cboSortOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelRestaurantLayout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelRestaurantLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panelRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelRestaurantLayout.createSequentialGroup()
                                .addComponent(btnMoveToAddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUploadCSV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRefreshTable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnQuit))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panelRestaurantLayout.setVerticalGroup(
            panelRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRestaurantLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(txtTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboSortBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboSortOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSort))
                .addGap(18, 18, 18)
                .addGroup(panelRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefreshTable)
                    .addComponent(btnQuit)
                    .addComponent(btnMoveToAddPanel)
                    .addComponent(btnUploadCSV))
                .addGap(30, 30, 30))
        );

        jTabbedPane.addTab("tab1", panelRestaurant);

        panelAddRestaurant.setBackground(new java.awt.Color(204, 255, 204));
        panelAddRestaurant.setPreferredSize(new java.awt.Dimension(562, 637));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblEmail.setText("LOCATION");

        lblName.setBackground(new java.awt.Color(255, 255, 255));
        lblName.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblName.setText("NAME");

        lblPhoneNo.setBackground(new java.awt.Color(255, 255, 255));
        lblPhoneNo.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblPhoneNo.setText("CUISINE");

        txtName.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE RESTAURANT INFO");

        btnContactList.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnContactList.setText("BACK");
        btnContactList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAddRestaurantLayout = new javax.swing.GroupLayout(panelAddRestaurant);
        panelAddRestaurant.setLayout(panelAddRestaurantLayout);
        panelAddRestaurantLayout.setHorizontalGroup(
            panelAddRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddRestaurantLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(panelAddRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddRestaurantLayout.createSequentialGroup()
                        .addGroup(panelAddRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelAddRestaurantLayout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnContactList))
                            .addGroup(panelAddRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelAddRestaurantLayout.createSequentialGroup()
                                    .addGroup(panelAddRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblPhoneNo))
                                    .addGap(11, 11, 11)
                                    .addGroup(panelAddRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtEmail)
                                        .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(panelAddRestaurantLayout.createSequentialGroup()
                                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddRestaurantLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(137, 137, 137))))
        );
        panelAddRestaurantLayout.setVerticalGroup(
            panelAddRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddRestaurantLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(panelAddRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAddRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAddRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(panelAddRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnContactList))
                .addContainerGap(298, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("tab2", panelAddRestaurant);

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("tab3", panelMenu);

        getContentPane().add(jTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, -1, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        int index;
        String search = txtSearch.getText();
        String type = cbSearchType.getSelectedItem().toString();


        txtSearch.setText("");
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUploadCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadCSVActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(this);
        File file = fileChooser.getSelectedFile();

        //populateContactTable();
    }//GEN-LAST:event_btnUploadCSVActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:

//        if (cl.isEmpty() == true) {
//            JOptionPane.showMessageDialog(rootPane, "CONTACT LIST IS EMPTY");
//        } else{
//            cName = JOptionPane.showInputDialog("ENTER THE NAME OF THE CONTACT TO EDIT:");
//            int index = cl.searchContactIndex(cName);
//            if (index != -1) {
//                cName = JOptionPane.showInputDialog("ENTER THE NEW NAME:", cl.contact.get(index).getName());
//                cEmail = JOptionPane.showInputDialog("ENTER THE NEW EMAIL:", cl.contact.get(index).getEmail());
//                cPhoneNo = JOptionPane.showInputDialog("ENTER THE NEW PHONE NUMBER:", cl.contact.get(index).getPhoneNo());
//                cl.editContact(cName, cEmail, cPhoneNo, index);
//                JOptionPane.showMessageDialog(rootPane, cName + " HAS BEEN SUCESSFULLY EDITED!");
//                populateContactTable();
//            } else {
//                JOptionPane.showMessageDialog(rootPane, cName + " WAS NOT FOUND IN THE CONTACT LIST.");
//            }
//        }

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
//        if (cl.isEmpty() == true) {
//            JOptionPane.showMessageDialog(rootPane, "CONTACT LIST IS EMPTY");
//        } else {
//            cName = JOptionPane.showInputDialog("ENTER THE NAME OF THE CONTACT TO DELETE:");
//            int index = cl.searchContactIndex(cName);
//            if (index != -1) {
//                JOptionPane.showMessageDialog(rootPane, cl.deleteContact(cName, index));
//                populateContactTable();
//            } else {
//                JOptionPane.showMessageDialog(rootPane, cName + " WAS NOT FOUND IN THE CONTACT LIST.");
//
//            }
//        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshTableActionPerformed
        // TODO add your handling code here:
        //populateContactTable();
    }//GEN-LAST:event_btnRefreshTableActionPerformed

    private void btnMoveToAddPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveToAddPanelActionPerformed
        // TODO add your handling code here:
        jTabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_btnMoveToAddPanelActionPerformed

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
        // TODO add your handling code here:
//        if (cl.isEmpty() == true) {
//            JOptionPane.showMessageDialog(rootPane, "CONTACT LIST IS EMPTY");
//        } else{
//            String condition = cboSortBy.getSelectedItem().toString();
//            String order = cboSortOrder.getSelectedItem().toString();
//            cl.sortContacts(condition, order);
//            populateContactTable();
//        }

    }//GEN-LAST:event_btnSortActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
//        cName = txtName.getText();
//        cEmail = txtEmail.getText();
//        cPhoneNo = txtPhoneNo.getText();
//
//        cl.addContact(cName, cEmail, cPhoneNo);
//        JOptionPane.showMessageDialog(rootPane, cName + " WAS SUCCESSFULLY ADDED!");
//        txtName.setText("");
//        txtEmail.setText("");
//        txtPhoneNo.setText("");
//        populateContactTable();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnContactListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactListActionPerformed
        // TODO add your handling code here:
        jTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_btnContactListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnContactList;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnMoveToAddPanel;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnRefreshTable;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSort;
    private javax.swing.JButton btnUploadCSV;
    private javax.swing.JComboBox<String> cbSearchType;
    private javax.swing.JComboBox<String> cboSortBy;
    private javax.swing.JComboBox<String> cboSortOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoneNo;
    private javax.swing.JPanel panelAddRestaurant;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelRestaurant;
    private javax.swing.JTable tblContactDetails;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNo;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
